Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

inherit_from: .rubocop_todo.yml

require: rubocop-rspec
