language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-19mode
services: mongodb
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
matrix:
  exclude:
    # not supported by Mongoid 3
    - rvm: 1.8.7
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/mongoid3.gemfile
